[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=50.0.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "liboqs-python>=0.16.0",
    "python-dotenv>=1.2.2",
    "uvicorn[standard]>=0.52.0",
]
